bbs: bubble_sort.c helpers.c
	gcc bubble_sort.c helpers.c -o bubble_sort
	./bubble_sort
		
ins: insertion_sort.c helpers.c 
	gcc insertion_sort.c helpers.c -o insertion_sort
	./insertion_sort

del: 
	rm *.exe
